#!/bin/sh
#
# http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/infrastructure/templates/rc.template
#
# See also: https://gist.github.com/anon987654321/4532cf8d6c59c1f43ec8973faa031103

rc_bg=YES
rc_reload=NO

daemon_user='spoints'
daemon='/usr/local/bin/spoints'
daemon_logger='daemon.info'

. /etc/rc.d/rc.subr

daemon_user='spoints'
pexp='ruby.*spoints'

rc_check() {
  pgrep -T "${daemon_rtable}" -q -f "${pexp}"
}

rc_stop() {
  pkill -T "${daemon_rtable}" -f "${pexp}"
}

rc_cmd $1
